apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-health-deployment    
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx-health-app    
    template:
        metadata:
            labels:
                app: nginx-health-app
        spec:
            containers:
            - name: nginx-health-app              
              image: sergusha/otus-architecture:task-01-updated
              ports:
                  - name: web
                    containerPort: 8000
              readinessProbe:
                  httpGet:
                      port: 8000
                      path: /health
                  initialDelaySeconds: 10
                  periodSeconds: 5
              livenessProbe:
                  httpGet:
                      port: 8000
                      path: /
                  initialDelaySeconds: 7
                  periodSeconds: 5
                  timeoutSeconds: 2